export const GET_PLAYER_INFO = 'GET_PLAYER_INFO';
export const GET_PLAYER_SCORE = 'GET_PLAYER_SCORE';
export const GET_GAME_TIMER = 'GET_GAME_TIMER';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const STOP_TIMER = 'STOP_TIMER';
