// actions`s file.
export const FETCH_DATA = 'FETCH_DATA';
export const GET_RESULTS = 'GET_RESULTS';
export const GET_ERROR = 'GET_ERROR';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const FILTER_BY_NUMERIC_VALUES = 'FILTER_BY_NUMERIC_VALUES';
export const FILTER_BY_COLUMN = 'FILTER_BY_COLUMN';
export const FILTER_BY_COMPARISON = 'FILTER_BY_COMPARISON';
export const FILTER_BY_VALUE = 'FILTER_BY_VALUE';
export const SELECTED_COLUMN = 'SELECTED_COLUMN';
export const SELECTED_RADIO = 'SELECTED_RADIO';
export const SORTED_COLUMN = ' SORTED_COLUMN';
